seed: 123
train_input_dir: /root/autodl-tmp/datasets/MDIR/train/input
train_target_dir: /root/autodl-tmp/datasets/MDIR/train/target
val_input_dir: /root/autodl-tmp/datasets/MDIR/val/input
val_target_dir: /root/autodl-tmp/datasets/MDIR/val/target
save_dir: /root/autodl-tmp/projects/IMD-net/checkpoints
model:
  img_channel: 3
  width: 32
  enc_blk_nums:
  - 4
  - 4
  - 4
  - 8
  middle_blk_num: 8
  dec_blk_nums:
  - 2
  - 2
  - 2
  - 2
  branch_num: 4
  tau: 0.2
train:
  patch_size: 256
  batch_size: 12
  accumulation_steps: 8
  num_workers: 4
  iterations: 800000
  lr: 0.0001
  min_lr: 1.0e-07
  val_every: 2000
  save_every: 2000
  amp: true
  clip_grad: 0.2
  weight_decay: 0.0001
loss:
  lambda_fft: 0.1
  delta_edge: 0.05
  gamma_decouple: 0.001
